### ISSUE TITLE
The converged pad and convolution NPU are not supported

### ISSUE THREAD

**Issue by xiaoyu1004** [ARM-software/ethos-n-driver-stack#12]
pad: pad_left: 1  pad_right: 1  pad_top: 1  pad_bottom: 1
convolution: dialation: 1 padding: VALID stride: 2  kernel_size: 3x3
After actual testing，the above convolution NPU is supported, but the NPU does not support the fusion of the two operators. The problem is that when the two operators are fused, the pad mode of convolution is SAME, which is supported by NPU documentation.

The NPU documentation is described as follows：

## Convolution 2D
- HWIO format weights are supported.
- The supported kernel heights and widths (the kernel does not have to be square) are: { 1, 2, 3, 5, 7, 9 }.
**- The supported strides (the height and width stride have to match) are: { 1, 2 }.**
- For kernels with height or width >7, only a stride of 1 is supported.
**- SAME and VALID padding are supported.**
- I*W/O must be between 2.33e-10 and 1, where:
     - I is the input quantization scale.
     - W is the weight quantization scale.
     - O is the output quantization scale.

**Comment by eleanorbonnici-arm** [comment]
Hi xiaoyu1004, 

thank you for your question. Could you please provide us with your input/output tensor sizes if the convolution you're running? 

Thanks, 
Eleanor

**Comment by xiaoyu1004** [comment]
> 

![image](https://user-images.githubusercontent.com/80047235/178387143-e62e122d-821d-4dac-8721-10c5595ad569.png)
The pad and convolution in the picture are fused during grath optimization, and NPU does not support it. The input size of pad is 1 x 320 x 320 x 32.

**Comment by xiaoyu1004** [comment]
> Hi xiaoyu1004,
> 
> Looking at the input, kernel sizes and striding you provided it seems that some of the padding will not be used. The driver stack checks for that so that might be the reason why the convolution comes out as unsupported together with the padding.
> 
> The solution might be to remove the padding on the right and bottom.
> 
> Let us know if that helps, Eleanor

Shouldn't you remove the left and top pad?  tensorflow's SAME pattern is on the right and bottom. We don't know how armnn works, right

**Comment by eleanorbonnici-arm** [comment]
Either way should work. We think that the issue is caused by a check that only checks whether all the padding is used considering tensor sizes. Removing padding from top and left to avoid superfluous padding should work too.

**Comment by eleanorbonnici-arm** [comment]
[xiaoyu1004](https://github.com/xiaoyu1004) Are you happy with the answer?

**Comment by xiaoyu1004** [comment]
> 
![image](https://user-images.githubusercontent.com/80047235/180772538-4732a239-dd90-4006-8902-0c608c3a438d.png)

Why do the operators in the figure above have different results on Arm CPU and NPU？

**Comment by xiaoyu1004** [comment]
> 
![image](https://user-images.githubusercontent.com/80047235/180772538-4732a239-dd90-4006-8902-0c608c3a438d.png)

Why do the operators in the figure above have different results on Arm CPU and NPU？

**Comment by eleanorbonnici-arm** [comment]
Hi [xiaoyu1004](https://github.com/xiaoyu1004), 

Thank you for sending the image. Could you please elaborate on your question a bit? Where do you see the difference between CPU and NPU?

**Comment by xiaoyu1004** [comment]
> Hi [xiaoyu1004](https://github.com/xiaoyu1004),
> 
> Thank you for sending the image. Could you please elaborate on your question a bit? Where do you see the difference between CPU and NPU?

![image](https://user-images.githubusercontent.com/80047235/180910860-cc74455a-1e0d-4056-bdd9-b3d2e16af8a0.png)
![image](https://user-images.githubusercontent.com/80047235/180911015-781f8488-75f0-43dc-861a-1c745602afa6.png)
I calculated the Euclidean distance between the CPU and the NPU result and found that the convolution of the same pattern was different.

**Comment by eleanorbonnici-arm** [comment]
Hi [xiaoyu1004](https://github.com/xiaoyu1004),

Could you please also share how you're getting these results? Are you using SPA, or running on an FPGA? 

Thank you

**Comment by xiaoyu1004** [comment]
> Hi [xiaoyu1004](https://github.com/xiaoyu1004),
> 
> Could you please also share how you're getting these results? Are you using SPA, or running on an FPGA?
> 
> Thank you

I am comparing the last output of the network on CPU and NPU，After debugging the latest results, we found that it is not because of the convolution SAME mode, but because of the error in the calculation of the resize bilinear interpolation. The RESIZE nearest neighbor interpolation has no problem, while the bilinear interpolation NPU calculation has problems. The test network structure is as follows:
![image](https://user-images.githubusercontent.com/80047235/181152072-9fa57b1f-6b27-4cf6-8704-d161b479b5fe.png)

**Comment by xiaoyu1004** [comment]
> Hi [xiaoyu1004](https://github.com/xiaoyu1004),
> 
> We suspect this is a bug in the current version of the software and planned to get this fixed in the 22.08 release.

Ok, thank you. I want to know when will 22.08 be released?

**Comment by eleanorbonnici-arm** [comment]
Hello [xiaoyu1004](https://github.com/xiaoyu1004),

Please accept an update to my previous message.
RESIZE bilinear with align_corners=false and half_pixel_centers=true is currently only supported with reduced accuracy due to hardware limitations. Resize in other configuration is possible without a loss in accuracy. We are planning to update the documentation to reflect this soon. 

Despite this loss of accuracy in the resize layer, is the overall accuracy of your network acceptable?

**Comment by xiaoyu1004** [comment]
> Hello [xiaoyu1004](https://github.com/xiaoyu1004),
> 
> Please accept an update to my previous message. RESIZE bilinear with align_corners=false and half_pixel_centers=true is currently only supported with reduced accuracy due to hardware limitations. Resize in other configuration is possible without a loss in accuracy. We are planning to update the documentation to reflect this soon.
> 
> Despite this loss of accuracy in the resize layer, is the overall accuracy of your network acceptable?
Ok, thank you. I tried other configurations, but the result of resize with reduced accuracy is unacceptable

**Comment by jslater8** [comment]
I see that the test network has half_pixel_centers set to true. It should be more accurate if that is turned off. Would that be a possibility for you to try?
