### ISSUE TITLE
An exception occurred using the cache network function

### ISSUE THREAD

**Issue by xiaoyu1004** [ARM-software/ethos-n-driver-stack#13]
I first changed the optimization options to save the compiled network, and then changed the optimization options again to load the network that was serialized to the file in the previous step, but there was an exception, which seems to be due to a format check error during deserialization

The execution log is as follows：
# ./object_detection_example  --model-file-path ./22W27-yolov5s-conv3-conv2-relu_640-int8.tflite   --label-path ./label.txt --preferred-backends EthosNAcc --img-path ./test.jpg --num-runs 1
Info: ObjectDetection example is running...
Info: ObjectDetection example profiling is running...
Info: ArmNN v29.0.0
Info: Initialization time: 0.41 ms.
Info: Network parsing time: 303.61 ms.
Debug: OptimizerOptions: 
	ReduceFp32ToFp16: 0
	ReduceFp32ToBf16: 0
	Debug: 0
	ShapeInferenceMethod: ValidateOnly
	ImportEnabled: 0
	ProfilingEnabled: 0
	ModelOptions: 
		Backend: EthosNAcc
			Option: SaveCachedNetwork
			Value: false
		Backend: EthosNAcc
			Option: CachedNetworkFilePath
			Value: /mnt/run/EthosN-CachingEndToEnd-TempFile.bin

Info: Optimization time: 304.33 ms.
Error: An error occurred when preparing the network workloads:  Not a serialized CompiledNetwork
Error: An error occurred when preparing the network workloads:  Not a serialized CompiledNetwork
terminate called after throwing an instance of 'armnn::Exception'
  what():  An error occurred when preparing the network workloads:  Not a serialized CompiledNetwork
Aborted
#

**Comment by eleanorbonnici-arm** [comment]
Hi [xiaoyu1004](https://github.com/xiaoyu1004), 

It's possible that the network didn't get properly serialised. Could you please share with us your code modifications to change optimization options and the log from the serialization run? 

The binary file would also help us with debug, how big is the file?

**Comment by eleanorbonnici-arm** [comment]
[xiaoyu1004](https://github.com/xiaoyu1004), do you still need help with this issue, or are you happy for it to be closed?
