### ISSUE TITLE
Error message while executing inference with NPU

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/ethos-n-driver-stack#14]
Hi,

We adopted two methods to compile our ArmNN inference code, the first method is compiling via Makefile and the other one is via CMakeLists. We logged the execution time from these compiling approaches and compared the results based on the same inference code, test image, and test model, and the logs are shown in the attachment.
[logs.zip](https://github.com/ARM-software/armnn/files/9207442/logs.zip)

However, the execution results contain the following error message:

Error: An error occurred attempting to execute a workload: An error has occurred waiting for the inference of a pre-compiled object: Timed out while waiting for the inference to complete
Why does the execution of NPU produce the error above? Since it takes time to reset the status of NPU, how to resolve the issue?

Best Regards

**Comment by jslater8** [comment]
Hi sorry for the delay, This issue seems quite involved and we need more information. Please contact us through your partner manager and dedicated support channels.

**Comment by jslater8** [comment]
Hi, I'm going to resolve this issue if there is no further question within a couple days. 

Thanks.
