### ISSUE TITLE
Ethos-N driver + simulated Ethos-N NPU?

### ISSUE THREAD

**Issue by shumeigiku** [ARM-software/ethos-n-driver-stack#15]
Hi all,

I want to introduce some security protections to Arm NPU. It requires to modify the NPU driver to collaborate with some access control in TF-A. Currently, I want to implement on Arm Ethos-N NPU driver, but I do not have a real Ethos-N NPU.

Thus, if I use some NPU simulator, such as SCALE-Sim (https://github.com/ARM-software/SCALE-Sim), to simulate the NPU, will the driver works with the simulator?

**Comment by jslater8** [comment]
Hi, 

There is no publicly available NPU simulator. Please talk to your partner manager so we can help you further.
