### ISSUE TITLE
Orange Pi 5B no driver file created after initializing the kernel module

### ISSUE THREAD

**Issue by federicoparra** [ARM-software/ethos-n-driver-stack#18]
Using Ubuntu 22.04 (5.10.160-rockchip kernel) with the SMMU config options as per your tutorial.

The firmware file was copied to the right folder, the ethosn.ko file initialized with sudo insmod ethosn.ko and it works:

dmesg | tail shows:
[ 8232.407774] Registering ethosn-main_allocator
[ 8232.410038] Registering ethosn-memory
[ 8232.411936] Registering ethosn-core

and lsmod shows:
ethosn                110592  0

and yet there is no device file:
$ ls /dev/ethosn*
ls: cannot access '/dev/ethosn*': No such file or directory

and so unit tests don't work etc.

What could be wrong?

**Comment by StefanaSimion** [comment]
Hello, please reach out through your partner manager so that we can assist you with this issue.

**Comment by federicoparra** [comment]
I don't have one. This is a hobby project I'm doing with an orange pi 5b

**Comment by StefanaSimion** [comment]
Thanks for clarifying - in that case, please note that this software driver is associated with the Arm® Ethos™-N Neural Processing Unit (NPU) and so will not be relevant to a system without this hardware.

**Comment by federicoparra** [comment]
Thank you I just realized today that the NPU in the Orange Pi 5B is *NOT* the Ethos one.
For anyone coming across this post, the right driver/software for the NPU contained in the Orange Pi 5B is this: https://wiki.t-firefly.com/en/ROC-RK3588S-PC/usage_npu.html
