### ISSUE TITLE
How can I get a device with Ethnos NPU?

### ISSUE THREAD

**Issue by fastpooh** [ARM-software/ethos-n-driver-stack#21]
Hello, I am interested in running several networks on arm Ethos NPU and check its power usage on android device.
However, I couldn't find a mobile device that has Ethos NPU in it.
Is there any way I can get a device with Ethos NPU?

**Comment by AndrzejKurek** [comment]
Hello @fastpooh and sorry for the late response!
Unfortunately, there is no mobile device available on the market with an Ethos-N NPU.
