### ISSUE TITLE
compilation error with scons

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/ethos-n-driver-stack#4]
Hi,

when I compile ethos-n driver with `scons`, I met the error 
`support_library/src/nonCascading/Strategies.cpp:737:66: error: '*((void*)(& bestParams)+4).ethosn::support_library::Strategy6::TrySetupAnyBlockConfig(ethosn::support_library::TensorConfig&, ethosn::support_library::SramAllocator&, const TensorShape&, const TensorShape&, const TensorShape&, ethosn::support_library::DataFormat, const TensorShape&, const std::vector<ethosn::command_stream::BlockConfig>&, const ethosn::support_library::HardwareCapabilities&, const ethosn::support_library::utils::ShapeMultiplier&, const ethosn::support_library::utils::ShapeMultiplier&, std::pair<bool, unsigned int>, ethosn::support_library::CompilerMceAlgorithm, uint32_t)::Strategy6Params::blockHeight' may be used uninitialized in this function [-Werror=maybe-uninitialized]
         tensorConfig.blockHeight = bestParams.value().blockHeight;
                                                                  ^
support_library/src/nonCascading/Strategies.cpp:736:65: error: '*((void*)(& bestParams)+4).ethosn::support_library::Strategy6::TrySetupAnyBlockConfig(ethosn::support_library::TensorConfig&, ethosn::support_library::SramAllocator&, const TensorShape&, const TensorShape&, const TensorShape&, ethosn::support_library::DataFormat, const TensorShape&, const std::vector<ethosn::command_stream::BlockConfig>&, const ethosn::support_library::HardwareCapabilities&, const ethosn::support_library::utils::ShapeMultiplier&, const ethosn::support_library::utils::ShapeMultiplier&, std::pair<bool, unsigned int>, ethosn::support_library::CompilerMceAlgorithm, uint32_t)::Strategy6Params::blockWidth' may be used uninitialized in this function [-Werror=maybe-uninitialized]
         tensorConfig.blockWidth  = bestParams.value().blockWidth;
                                                                 ^
cc1plus: all warnings being treated as errors
scons: *** [support_library/build/release_native/src/nonCascading/Strategies.o] Error 1
scons: building terminated because of errors.
`
Does anyone know how to solve these errors?

**Comment by jslater8** [comment]
Hi, 

Thanks for raising this issue. We've seen this before when compiling with older versions of g++. We have fixed this specific error in the upcoming release. The known version of g++ that works is 7.5, this is the default which is packaged with Ubuntu 18.04.

**Comment by Rahn80643** [comment]
Hi,
Thank you for informing the version of g++, I can successfully build ethos-n-driver-stack with scons.
However, when I tried to build ARM NN with ethos-n, I met the following error:
`/EthosNSubgraphViewConverter.cpp:96:50: error: ‘using element_type = class armnn::ConstCpuTensorHandle {aka class armnn::ConstCpuTensorHandle}’ has no member named ‘GetTensor’; did you mean ‘GetTensorInfo’?

EthosNSubgraphViewConverter.cpp:96:60: error: expected primary-expression before ‘void’`
![armnn_compile_error](https://user-images.githubusercontent.com/8951991/117092583-48e89f80-ad91-11eb-9c4e-671de701ab59.png)

I use ARM NN 21.02 with argmax path in [link](https://github.com/ARM-software/armnn/commit/28f177c45cb8e23b86c9f3ff435921183340fc33).
Does this error occur because the version of ARM NN, or should I modify `GetTensor` to `GetTensorInfo` in ethos source code?

**Comment by jslater8** [comment]
Hi,

It appears the version of Arm NN you are using isn't 21.02. It seems that it was commited in April. The 21.02 release branch is here. https://github.com/ARM-software/armnn/commit/175ed68c8a22e623183c5e8fba4b65ca6d38b858. Is there a specific reason you needed this commit?

**Comment by Rahn80643** [comment]
Hi,
Since the model I'm using contains an Argmax layer. The ParseArgMinMax function in original 21.02 release contains some issues, so I updated my ARM NN to (this patch)[https://github.com/ARM-software/armnn/commit/28f177c45cb8e23b86c9f3ff435921183340fc33] to make ARM NN execute my model successfully

Rahn

**Comment by jslater8** [comment]
Ah I see, thanks for the context. Unfortunately we haven't yet released a version of our driver stack to support this version of Arm NN. The 21.05 release of Arm NN and our driver stack will include this patch and will land at the end of may. If its urgent and it's not possible to remove the argmax, you could try modifying the source code, although there may be a large number of changes needed.
