### ISSUE TITLE
Support of elementwise mulitiplication

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/ethos-n-driver-stack#6]
Hi,
Arm NN Ethos-N backend 21.08 supports multiplication of a variable by a scalar constant. Does this means Ethos-N backend 21.08 currently does not support the operation of elementwise multiplication for multiplying two tensors?

Best regard,
Rahn

**Comment by mikaelolsson-arm** [comment]
Hi,

Thanks for your question.

The Arm NN Ethos-N NPU backend 21.08 does not support element-wise multiplication of two tensors.

Thanks,
Mikael
