### ISSUE TITLE
SPA test generates warning "Layer of type is not supported"

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/ethos-n-driver-stack#7]
Hi,
We have a license to use a SPA program, and we analyze modified BiSeNetv2 models with the SPA program for evaluating NPU. During the analysis process of modified BiSeNetv2 int8 and uint8 model, we met the following warning respectively:

(uint8): Layer of type Resize is not supported on request backend EthosNAcc for input data type QAsymmU8 and output data type QAsymmU8
![14950996264721](https://user-images.githubusercontent.com/8951991/138428954-9a59bf66-2cd2-4ddd-bd36-f8e5bcae6c87.png)

(int8): Layer of type DepthwiseConvolution2d is not supported on request backend EthosNAcc for input data type QAsymmS8 and output data type QAsymmS8
![14950997786476](https://user-images.githubusercontent.com/8951991/138428910-42e2d75c-5c89-4531-8b9b-4459c177cd62.png)

We want to ask:
1. whether the warning messages above affect the results when using a physical NPU?
2. The warning messages informs the layer is falling back to the next backend, will the unsupported layer be executed on GPU or CPU?

Best Regards,
Rahn

**Comment by Rahn80643** [comment]
Hi, 
The version of the SPA program is R1P3, which generates the warning messages above. Is there any SPA program equipped with the latest Ethos-N driver?

Best Regards,
Rahn

**Comment by jslater8** [comment]
Hi, sorry for the late response.

It looks like from your response in https://github.com/ARM-software/ethos-n-driver-stack/issues/8 you tried 21.08 for Arm NN and the Compute Library, did you try it for the Ethos-N driver, it should resolve the warnings for depthwise convolutions.

Thanks,
Josh

**Comment by zingo** [comment]
Hi @Rahn80643 do you have anything you want to follow up with? I'm wondering if we can close this ticket?

**Comment by Rahn80643** [comment]
Hi, @zingo 
We don't have anything to follow up with, please close this ticket.

Thank you,
Rahn
