### ISSUE TITLE
Inference result of int8 model on NPU

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/ethos-n-driver-stack#8]
Hi, 
We've tested an int8 model with ArmNN 21.08 and Compute Library 21.08 patch, which solves the [issue](https://github.com/ARM-software/armnn/issues/557) of wrong result in int8 models.

To further evaluate the results on NPU, we want to ask that if we apply the same tflite model on NPU, will the inferred results contain noise or the results be identical to TFLite API?

Best regards,
Rahn

**Comment by jslater8** [comment]
Hi, sorry for the late response.

The NPU will not have identical results to the TFLite interpreter. We don't think should this should impact real world use cases though. 

Thanks,
Josh

**Comment by zingo** [comment]
Hi @Rahn80643 do you have anything you want to follow up with? I'm wondering if we can close this ticket for now and reopen or create a new if something pops up?

**Comment by Rahn80643** [comment]
Hi, @zingo 
We don't have anything to follow up with currently, please close this ticket.

Thank you,
Rahn

**Comment by zingo** [comment]
Thanks! Take care!
